### ISSUE TITLE
Community plugin pages can be hard to read

### ISSUE THREAD

**Issue by Farow** [Nilahn/pine_forest_berry#1]
I'm using the light theme and when opening the page of a plugin, the background color is `#CCCCCC`, which makes the readability of H3 headings and code blocks particularly difficult.

I'm currently using the following snippet to adjust the background color.

```
.community-plugin-details {
    background: #F2F2F2;
}
```

**Comment by Nilahn** [comment]
Hi Farow, thanks for the feedback! I've noticed that as well, actually. Not only in the plugin's menu, but in the themes-menu as well. I'll be working something out soon.

**Comment by Farow** [comment]
Another issue that I've noticed is that tags are also hard to read when using the light theme, since their color is set to white.
