### ISSUE TITLE
Fallbacks for monospace font

### ISSUE THREAD

**Issue by challah** [Nilahn/pine_forest_berry#2]
Hello! Nice theme. 
I don't have Monaco installed, so my code blocks look like this at first, as the font is set to `font-family: monaco !important;`
![2021-11-19 08_25_25-Jorvault - Obsidian v0 12 19](https://user-images.githubusercontent.com/13334709/142631479-9d0306ec-bb4d-4076-9a74-78a224198982.png)

I modified my stylesheet and changed instances of that to the variable, which does have other monospace fallbacks.
```
font-family: var(--font-family-editor);
```

(Additionally, I think this is only an issue with this specific plugin - but the background-color and color for the copy button in the markdown highlighter plugin shown above are very similar so I tweaked it a bit too)

Thanks!

**Comment by Nilahn** [comment]
Hi challah, thank you for your feedback! I'm glad you like the theme. 
I meant to go through the plugins I have installed (as a start) and check for any hickups, just haven't gotten around to it. Thanks for the heads up!
