### ISSUE TITLE
Font size & Quick font size adjustment

### ISSUE THREAD

**Issue by galderna** [Nilahn/pine_forest_berry#3]
Love the pine_forest_berry theme.

I've just tried setting the Font size to something other than the default, both manually and via "Quick Adjust Font Size" (touchpad), but unfortunately to no avail. However I found no problem at all with other themes, in particular, the Obsidian default one...

Obsidian Version 0.15.9 (installer 0.15.8)
Mac OS X 10.14.6 (Mojave)

Thank you very much for your great work.

**Comment by Nilahn** [comment]
Hi galderna!

Sorry for the late reply. I'm having a baby any day now and I'm a little preoccupied with that, but thank you for your feedback and I will get on that, as soon as I have the capacity! In the meantime, if you maybe want to tweak around yourself: I would go about this by just looking at the code of other themes where the Font Size can be adjusted and compare how they wrote it differently. And feel free to share, if you find anything!

**Comment by aliyeYM** [comment]
Hello, I like this topic very much！！！
I would like to ask whether the problem that the font size cannot be changed has been solved. 
Thank you！！

**Comment by Aceitun4** [comment]
Hello! I really love this theme but I have an issue about that. It doesn´t recognize this command: ctrl + scroll or cmd + scroll.

Thank you!!!

![Captura de pantalla 2023-01-20 a las 0 02 30](https://user-images.githubusercontent.com/123128016/213581567-d409e191-be4b-48dc-b6dd-a464e7a39c01.png)

**Comment by vani-lu** [comment]
You can remove the lines defining editor font size, and let obsidian use the default ones. This worked for me – the editor adjusts to the font size settings. I don't use reading mode, so I don't know the influence on that.
